### ISSUE TITLE
Optimise loading of map and assets, and the rendering of map and objects

### ISSUE THREAD

**Issue by nginyc** [nginyc/Magna-Caves#58]
We'll need to cut down on duplicate code (all the tiles and tile properties that stay constant) across all .tmx level files. As similar to what the code is already trying to do, we aim to have all tile properties and animations on a "master" game .tsx/.tmx file (which will be preloaded) and have each level .tmx file contain only minimal data of layers and cells for the level.

Now that we're using a great number of tiles and therefore separate images, we should look to combine all of the images into a single spritesheet image so that loading can be done faster (and to use less memory).

**Comment by ckjr** [comment]
Currently using TexturePacker. https://www.codeandweb.com/texturepacker

There's support for spritesheets for lidgdx. 

Sample :
```
Menu1.png
size: 1497, 1011
format: RGBA8888
filter: Linear,Linear
repeat: none
Completion Screen/Bar Background
  rotate: false
  xy: 1, 957
  size: 504, 30
  orig: 504, 30
  offset: 0, 0
  index: -1
Completion Screen/Orange Liquid
  rotate: false
  xy: 1, 989
  size: 490, 14
  orig: 506, 30
  offset: 8, 8
  index: -1

**Comment by nginyc** [comment]
I will continue to look into this, and the possibilities to also optimize the rendering of objects/tiled map and improve game performance (the occasional lag spike issue)

**Comment by nginyc** [comment]
Currently in the works: Using of libgdx's TextureAltas for both user interface's graphics and game's graphics. Spritesheets will be used so that the game doesn't need to load too many files. This is concurrent with the rework of how game maps would be encoded, organised and parsed - issue #66

**Comment by nginyc** [comment]
Through pre-processing, all graphics, both menu's and the tiled map's, are now loaded in spritesheets, and the whole thing is working fine after a few days of testing on the Spritesheeted branch, which has been merged with the master branch. 
All maps are also pre-processed and only the minimal processed maps (all pointing to a single, generated tileset file) are included in the game. The size of the game has reduced greatly to 12MB (for desktop) and 3MB (for .apk)
