### ISSUE TITLE
Issue with the stars system

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magna-Caves#61]
1. Too small in the mobile version
2. Should the player be able to get 0 stars? (Probably no)

**Comment by ckjr** [comment]
Currently, it is not very intuitive in design because it takes a second glance to tell if the player is currently at 2 stars or at 3 stars. Sometimes the stars are too close together as well, although that might be just the issue of the values being too close together.

**Comment by nginyc** [comment]
Agree on the above pointers. 
I'm suggesting a change in design for the player move bar:
- At the start, the bar drains linearly as the player moves, with the full length of the bar proportionate to the moves for 3 stars, and only shows the milestone for 3 stars at the very left
- When the player drops below 3 stars, the 2 stars now replaces the 3 stars, and the full length of bar becomes proportionate to the moves for 2 stars, and the bar sort of adjusts based on this (current player moves / moves for 2 stars)
- 1 star would be the minimum for any level, so when the player drops below 2 stars, the bar will be kept emptied and there can be some indication of that the player only has 1 star
- There could be change in placement of the stars, to be placed just below/above the bar, to indicate the current stars for the player clearly

**Comment by nginyc** [comment]
Implemented a new design for player moves bar
